### ISSUE TITLE
change color or hide with some states?

### ISSUE THREAD

**Issue by unosakk** [queimadus/last-changed-element#5]
any interest in developing this further?
i'd like to see color change or text be hidden when, lets say there is not motion. Only show last change when motion is triggered.

`show_state: 'on'`
or
`state_color:
    'on' : red
    'off' : grey
`

**Comment by queimadus** [comment]
Don't have a lot of time on hands for this but I think you can achieve the intended results with:

- Using [picture-elements#conditional-element](https://www.home-assistant.io/dashboards/picture-elements/#conditional-element) instead of `show_state: 'on'`
- Using [card-mod](https://github.com/thomasloven/lovelace-card-mod) instead of `state_color: 'on' : red 'off' : grey`

**Comment by vogtmh** [comment]
I use this code to display the last_changed state whenever the washing machine switches to running mode:

![Bildschirmfoto 2023-09-14 um 20 47 24](https://github.com/queimadus/last-changed-element/assets/37808063/76bae3ea-77db-4876-b68c-5b96305db3a9)
